virkshop:
    projectLinks:
        "$PROJECT_FOLDER/commands":      "$VIRKSHOP_FOLDER/@project/commands"
        "$PROJECT_FOLDER/documentation": "$VIRKSHOP_FOLDER/mixture/documentation"
        "$PROJECT_FOLDER/events":        "$VIRKSHOP_FOLDER/mixture/events"
        "$PROJECT_FOLDER/settings":      "$VIRKSHOP_FOLDER/mixture/settings"
    
    debuggingLevel: 1